server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Tout ce qui commence par /api/ est envoyé au conteneur backend
    location / {
        try_files $uri $uri/ =404;
    }
    
    # /form/2, /form/15... -> toujours la même page, le JS lit l'id dans l'URL
    location ~ ^/form/[0-9]+/?$ {
        try_files /form.html =404;
    }

    location /api/ {
        proxy_pass http://backend:3000;
    }

}